name: Deployment of ${{ github.ref }} on commit ${{ github.sha }}

on:
  push:
    tags:
    - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-test: # Keep this job synchronized across all workflows.
    runs-on: ubuntu-latest

    steps:
    # # # # # # # # # # # # # # # # # # # # # # # # # # #
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 1

    # # # # # # # # # # # # # # # # # # # # # # # # # # #
    # Caching Docker images would be nice, but see https://github.com/actions/cache/pull/37 for the problems.

    # # # # # # # # # # # # # # # # # # # # # # # # # # #
    - name: Build
      run: ./build.sh

    # # # # # # # # # # # # # # # # # # # # # # # # # # #
    - name: Test
      run: ./test.sh

    # TODO: create package and send that to the artifact storage.

  # TODO: create release and attach package to it.
